name: "문서화 작업"
description: "문서화 작업"
labels: "📝 Docs"
title: "📝 Docs: "
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: 설명을 입력하세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Todo
      placeholder: "- [ ] todo1\n- [ ] todo2"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Etc
      placeholder: 기타 설명
    validations:
      required: false
