name: "기능 구현"
description: "기능 구현 이슈 템플릿"
labels: "✨ Feature"
title: "✨ Feature: "
body:
  - type: textarea
    attributes:
      label: Description
      placeholder: 설명을 입력하세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Todo
      placeholder: "- [ ] todo1\n- [ ] todo2"
    validations:
      required: false
  - type: textarea
    attributes:
      label: Etc
      placeholder: 기타 설명
    validations:
      required: false
