name: "오류 수정"
description: "오류 설명 및 수정"
labels: "🐞 Bug"
title: "🔨 Fix: "
body:
  - type: textarea
    attributes:
      label: 🤔 오류 내용
      placeholder: 오류 내용 및 오류 발생 상황을 알려주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🚩 오류 발견 위치
      placeholder: 오류 발견 위치를 작성해 주세요!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Etc
      placeholder: 기타 설명
    validations:
      required: false
