name: "리팩토링"
description: "코드 리팩토링 및 구조 개선 템플릿"
labels: "🔨 Refactor"
title: "🔨 Refactor: "
body:
  - type: textarea
    attributes:
      label: 리팩토링 대상
      placeholder: 리팩토링할 대상을 설명해주세요!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📢 리팩토링 이유
      placeholder: 리팩토링을 하게된 이유에 대해 설명해주세요!
    validations:
      required: false
  - type: textarea
    attributes:
      label: Etc
      placeholder: 기타 설명
    validations:
      required: false
